version: '3'
services:
  frontend:
    build: ./frontend
    ports:
     - "8000:80"

  backend:
    build: ./backend
    ports:
     - "8080:8080"

  redis:
    image: redis
    ports:
     - "6379:6379"
