version: '3.6'
services:
  frontend:
    build: ./frontend
    environment: 
     - BACKEND_URL=http://localhost:8888
    ports:
     - "8000:80"

  proxy:
    build: ./proxy
    environment: 
     - TARGET_URL=http://backend:8080
     - PYTHONUNBUFFERED=1
     - APP_VERSION=green
    ports:
     - "8888:8888"

  backend:
    build: ./backend
    environment: 
     - APP_VERSION=red
    ports:
     - "8080:8080"

  redis:
    image: redis
    ports:
     - "6379:6379"
