version: '3.7'
services:
  jenkins:
    build: .
    # image: jenkins/jenkins:lts
    # privileged: true
    # user: root
    ports:
      - 8081:8080
      # - 50000:50000
    container_name: jenkins
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/com.docker.cli:/usr/bin/com.docker.cli:ro # only on WSL installation
      - /usr/bin/docker:/usr/bin/docker:ro
      - /usr/bin/docker-compose:/usr/bin/docker-compose:ro
 